{{- $namespace := .Release.Namespace -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ $namespace }}
data:
  {{- $files := .Files }}
  {{- range tuple "config.yaml"}}
  {{ . }}: {{ toYaml ($files.Get .) | indent 2}}
  {{- end }}