apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      #app.kubernetes.io/name: {{ template "fullname" . }}
      #app.kubernetes.io/managed-by: Helm
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalHTTPSecondaryPort }}
        - containerPort: {{ .Values.service.internalHTTPPort }}
        - containerPort: {{ .Values.service.internalGRPCPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalHTTPSecondaryPort }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.service.internalHTTPSecondaryPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-configmap
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
