{{- if .Values.ingress.enabled -}}
{{- $usePath := .Values.ingress.usePath -}}
{{- $namespace := .Release.Namespace -}}
{{- $workflow := .Values.workflow -}}
{{- $serviceName := .Values.service.name -}}
{{- $servicePort := .Values.service.externalHTTPPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.prefix }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.service.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "name" . }}
spec:

  rules:
  {{- if eq $namespace $workflow }}
  {{- range .Values.ingress.hostBased.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
  {{- end -}}
  {{- end }}
  {{- range .Values.ingress.pathBased.hosts }}
  - host: {{ . }}
    http:
      paths:
      {{- if eq $namespace $workflow }}
      - path: /{{ $serviceName }}
        pathType: Prefix
      {{- else }}
      - path: /{{ $namespace }}/{{ $serviceName }}(/|$)(.*)
        pathType: Prefix
      {{- end }}
        backend:
          service:
            name: {{ $serviceName }}
            port:
              number: {{ $servicePort }}
  {{- end }}
  tls:
  {{- if eq $namespace $workflow }}
  {{- if .Values.ingress.hostBased.tls }}
{{ toYaml .Values.ingress.hostBased.tls | indent 2 }}
  {{- end -}}
  {{- end }}
  {{- if .Values.ingress.pathBased.tls }}
{{ toYaml .Values.ingress.pathBased.tls | indent 2 }}
  {{- end -}}
{{- end -}}
